name: Terraform deployments

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'terraform/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.filter.outputs.changed_dirs }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Detect changes in Terraform directories
        id: filter
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^terraform/' || true)

          changed_dirs=$(echo "$changed_files" | awk -F'/' '{print $1"/"$2}' | sort -u | jq -R . | jq -s .)

          echo "Changed Terraform directories: $changed_dirs"
          echo "changed_dirs=$changed_dirs" >> $GITHUB_OUTPUT

  terraform:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect-changes.outputs.changed_dirs != '[]' }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changes.outputs.changed_dirs) }}

    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: Plan Terraform
        run: |
          terraform init
          terraform plan -out=tfplan

      - name: Apply Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          terraform init
          terraform apply -auto-approve tfplan

